export const influencerTypes = [
  { value: 'ATLETA', label: 'Atleta' },
  { value: 'ARTISTA', label: 'Artista' },
  { value: 'CLUBE', label: 'Clube' },
  { value: 'IGREJA', label: 'Igreja' },
  { value: 'INFLUENCER_DIGITAL', label: 'Influencer Digital' },
  { value: 'ONG', label: 'ONG' },
  { value: 'TIME_ESPORTIVO', label: 'Time Esportivo' },
  { value: 'COMERCIANTE', label: 'Comerciante' },
  { value: 'CELEBRIDADE', label: 'Celebridade' },
  { value: 'MUSICO', label: 'Músico' },
  { value: 'ATOR_ATRIZ', label: 'Ator/Atriz' },
  { value: 'COMEDIANTE', label: 'Comediante' },
  { value: 'MODELO', label: 'Modelo' },
  { value: 'CHEF_CULINARISTA', label: 'Chef/Culinarista' },
  { value: 'ESPECIALISTA_EM_TECNOLOGIA', label: 'Especialista em Tecnologia' },
  { value: 'GAMER', label: 'Gamer' },
  { value: 'BLOGUEIRO', label: 'Blogueiro' },
  { value: 'VLOGGER', label: 'Vlogger' },
  { value: 'PODCASTER', label: 'Podcaster' },
  { value: 'ESPECIALISTA_EM_FINANCAS', label: 'Especialista em Finanças' },
  { value: 'ESPECIALISTA_EM_SAUDE', label: 'Especialista em Saúde' },
  { value: 'PERSONAL_TRAINER', label: 'Personal Trainer' },
  { value: 'COACH', label: 'Coach' },
  { value: 'INFLUENCER_DE_MODA', label: 'Influencer de Moda' },
  { value: 'INFLUENCER_DE_BELEZA', label: 'Influencer de Beleza' },
  { value: 'INFLUENCER_DE_VIAGEM', label: 'Influencer de Viagem' },
  { value: 'INFLUENCER_DE_LIFESTYLE', label: 'Influencer de Lifestyle' },
  { value: 'EDUCADOR', label: 'Educador' },
  { value: 'JORNALISTA', label: 'Jornalista' },
  { value: 'POLITICO', label: 'Político' },
  { value: 'ATIVISTA', label: 'Ativista' },
  { value: 'EMPREENDEDOR', label: 'Empreendedor' },
  { value: 'CIENTISTA', label: 'Cientista' },
  { value: 'ESCRITOR', label: 'Escritor' },
  { value: 'FOTOGRAFO', label: 'Fotógrafo' },
  { value: 'DESIGNER', label: 'Designer' },
  { value: 'HUMORISTA', label: 'Humorista' },
  { value: 'DANÇARINO', label: 'Dançarino' },
  { value: 'DJ', label: 'DJ' },
  { value: 'INFLUENCER_DE_PETS', label: 'Influencer de Pets' },
  { value: 'INFLUENCER_DE_GAMES', label: 'Influencer de Games' },
  { value: 'INFLUENCER_DE_TECNOLOGIA', label: 'Influencer de Tecnologia' },
  {
    value: 'INFLUENCER_DE_SUSTENTABILIDADE',
    label: 'Influencer de Sustentabilidade',
  },
  {
    value: 'INFLUENCER_DE_PARENTALIDADE',
    label: 'Influencer de Parentalidade',
  },
  { value: 'OUTRO', label: 'Outro' },
];

export const genderList = [
  { value: 'FEMININO', label: 'Feminino' },
  { value: 'MASCULINO', label: 'Masculino' },
  { value: 'MULHER_TRANS', label: 'Mulher Trans' },
  { value: 'HOMEM_TRANS', label: 'Homem Trans' },
  { value: 'AGENDER', label: 'Agênero' },
  { value: 'GENERO_FLUIDO', label: 'Gênero Fluido' },
  { value: 'INTERSEXO', label: 'Intersexo' },
  { value: 'NAO_BINARIO', label: 'Não-binário' },
  { value: 'QUEER', label: 'Queer' },
  { value: 'OUTRO', label: 'Outro' },
  { value: 'PREFIRO_NAO_DIZER', label: 'Prefiro não dizer' },
];
